sudo: required
dist: trusty
language: python
python:
  - 3.5

before_install:
  - sudo apt-get update -qq

install:
  - pip install tensorflow gpflow pytest pytest-xdist pytest-cov codecov
  - python setup.py install

script:
  - pytest -W ignore::UserWarning --durations=50 --cov=./odvgp -d --tx 3*popen//python=python3.5 --pyargs ./tests
  - codecov --token=4ac7ec1d-3921-4378-be0e-ec6f774655d1

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download