sudo: required
dist: trusty
language: python
python:
  - 3.5

before_install:
  - sudo apt-get update -qq

install:
  - pip install numpy scipy sklearn pandas pytest matplotlib pytest-xdist pytest-cov codecov ddt
  - python setup.py install
  - git clone https://github.com/GPflow/GPflow.git
  - cd GPflow
  - pip install .
  - cd ../

script:
  - pytest -W ignore::UserWarning --durations=50 --cov=./odvgp -d --tx 3*popen//python=python3.5 --pyargs ./tests
  - codecov --token=fe99b84e-0656-4739-96b9-79f021477eac

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download